language: php

php:
  - 7.4

env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"

before_script:
  - if [ "$DEPENDENCIES" = "high" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" = "low" ]; then composer --prefer-lowest update; fi;

script:
  - ./vendor/bin/phpunit
  - ulimit -n 4096 && phpdbg -qrr ./vendor/bin/infection --min-msi=100 --min-covered-msi=100
  - php -n ./vendor/bin/phpbench run --report=aggregate --revs=500 --iterations=50 --warmup=3
  # Only run the code standards with the latest package
  - ./vendor/bin/phpcs
  - ./vendor/bin/roave-backward-compatibility-check
